dependencies {
    compileOnly(libs.jetbrains.annotations)

    // LDLib
    jarJar(api(forge.ldlib.get()))

    // Registrate
    jarJar(api(forge.registrate.get()))

    // Configuration
    // jarJar(api(forge.configuration.get()))
    jarJar(api("curse.maven:configuration-444699:6779573"))
    // Recipe Viewers
    compileOnly(forge.bundles.jei)
    compileOnly(forge.bundles.rei)
    compileOnly(forge.emi)

    // WAILA-likes
    compileOnly(forge.jade)

    // KJS
    compileOnly(forge.bundles.kjs)

    // Teams
    compileOnly(forge.ftblibrary)
    compileOnly(forge.ftbteams)
    compileOnly(forge.ftbquests)
    compileOnly(forge.resourcefullib)
    compileOnly(forge.argonauts)
    compileOnly(forge.heracles)

    // Maps
    compileOnly(forge.ftbchunks)
    compileOnly(forge.xaeroslib)
    compileOnly(forge.xaerosminimap)
    compileOnly(forge.xaerosworldmap)
    compileOnly(forge.journeymap.api)
    compileOnly(forge.journeymap.forge)

    // Standard runtime mods //
    localRuntime(forge.jade)
    localRuntime(forge.spark)
    localRuntime(forge.modernfix)

    // Runtime Recipe Viewers - uncomment whichever one you want to use //
    localRuntime(forge.emi)
//    localRuntime(forge.jei.forge.impl)
//    localRuntime(forge.bundles.rei.runtime)

    // Client-only runtime mods //
    clientLocalRuntime(forge.sodium)
    clientLocalRuntime(forge.iris)

    //////////////////////////////////////////////////////
    // Runtime mods for dev testing with unclean client //
    //////////////////////////////////////////////////////
    extraLocalRuntime(forge.bundles.kjs)

    extraLocalRuntime(forge.ftblibrary)
    extraLocalRuntime(forge.ftbteams)
    extraLocalRuntime(forge.ftbquests)

//    extraLocalRuntime(forge.heracles)
    extraLocalRuntime(forge.resourcefullib)

//    extraLocalRuntime(forge.xaerosminimap)
//    extraLocalRuntime(forge.xaerosworldmap)
    extraLocalRuntime(forge.journeymap.forge)
    extraLocalRuntime(forge.ftbchunks)

    extraLocalRuntime(forge.bookshelf) {
        transitive = false
    }

    extraLocalRuntime(forge.kotlinforforge) {
        transitive = false
    }
    extraLocalRuntime(forge.observable)
    //////////////////////////

    testImplementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
}
