org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true

# Mod Info
mod_id = gtmogs
mod_name = GregTech Modern Ore Gen Standalone
mod_version = 1.0.6-pcmc.6
mod_description = GregTech Modern's ore generation and integrations with absolutely no other content.
mod_license = LGPL-3.0 license
mod_url = https://github.com/fmbellomy/gtmogs
mod_issue_tracker = https://github.com/fmbellomy/gtmogs/issues/
maven_group = com.quantumgarbage
